
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10

  target: itg
  outputs:
    itg:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: hogehoge
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10