
version: '3'
services:
    embulk:
      container_name: embulk
      build: ./embulk
      volumes:
        - "./data/embulk:/app"
      tty: true

    postgres:
      container_name: postgres2
      shm_size: '1gb'
      image: postgres:14-alpine
      ports:
        - "5431:5432"
      #volumes:
      #  - "./data/postgres/data:/usr/local/pgsql/data"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      restart: always