version: '3'
services:
    embulk:
      container_name: embulk
      build: ./embulk
      volumes:
        - "./data/embulk:/app"
        - "./data/digdag:/app/digdag"
      env_file:
          - ./.env
      tty: true

    postgres:
      container_name: postgres2
      shm_size: '1gb'
      image: postgres:14-alpine
      ports:
        - "5430:5432"
      #volumes:
      #  - "./postgresql/config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      restart: always

    dbt:
      container_name: dbt
      build: ./dbt
      volumes:
        - "./data/dbt/dbt_projects:/usr/app/dbt"
        - "./data/digdag_dbt:/app/digdag"
      ports:
        - "65432:65432"
        - "65433:65433"